//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DedeAndres_2001544801_Assigment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string WatchName { get; set; }
        public int WatchPrice { get; set; }
        public string WatchPic { get; set; }
        public int Stock { get; set; }
    }
}
